- src/components/Page/Posts/Media/Images.vue
- src/components/Page/Posts/Post.vue
- src/components/Page/Posts/Post/AddMedia.vue
- src/components/Page/Posts/Post/DoPost.vue
- src/components/Page/Posts/Post/PostStore.ts
- src/pages/Posts.astro
client:only="vue"に指定すると、Astroで用意されている状態管理のnanostoresでエラーが起きるので使わないように変更
> remove nanostores

- src/components/Page/Posts/Post.vue
- src/components/Page/Posts/Post/DoPost.vue
- src/index.ts
completes https://www.pivotaltracker.com/story/show/185612056
- sends up user signature
- verifies address on the backend
> verify address on server

- src/constants/example-posts.ts
- src/types.ts
Add example reactions to src/constants/example-posts.ts and its typing.
> Add example reactions

- package.json
- yarn.lock
sets "@astrojs/tailwind" dependency to static
> resolves breaking tailwind styles

- src/components/Page/Index.vue
- src/components/Page/Posts/Post.vue
on successfully posting, add that post to the posts list
> adds post to feed on success

- preview/src/pages/[...page].astro
- preview/src/theme/Connect.vue
- src/components/Page/Index.vue
moves connect button into preview
> Remove connect

- src/apiHandler/reactions.ts
- src/db/redis.ts
> bugfix: reaction updating is not working

- src/components/Page/Index.vue
- src/index.ts
> Add editor validation to frontend

- package.json
- src/components/Page/Posts/Media/Images.vue
- yarn.lock
I've added the image viewer using https://photoswipe.com/.
> Add Image Viewer

- src/components/Page/Posts/Comment.vue
- src/constants/example-posts.ts
Fixes a bug where it was failing to fetch profile in the comments section
> passes property address to profile component in comments section

- package.json
- src/apiHandler/comment.ts
- src/apiHandler/reactions.ts
Removes the mock authentication used for testing
> Enable authentication

- src/components/Page/Index.vue
- src/fixtures/masking.ts
- Put Account verify button
- Do not mask when owner on sever 
https://github.com/dev-protocol/clubs-plugin-posts/assets/41713089/e2461b07-f1db-4fe2-96ad-2fa3c1c06109
> Verify button & Do not mask when owner

- preview/config.ts
- src/apiHandler/comment-encoded-redis.ts
- src/apiHandler/comment.ts
- src/apiHandler/copy-encoded-redis_to_documents-redis.ts
- src/apiHandler/posts-encoded-redis.ts
- src/apiHandler/posts.ts
- src/apiHandler/reactions-encoded-redis.ts
- src/apiHandler/reactions.ts
- src/constants/redis.ts
- src/db/index.ts
- src/db/redis-documents.ts
- src/db/redis.ts
- src/db/uuidFactory.ts
- src/index.ts
> Supports document DB on Redis 

- package.json
- src/components/Page/Index.vue
- src/components/Page/Posts/Post.vue
Fixes 2 bugs:
-  fix a bug that all memberships are displayed as the required memberships
-  fix a bug that updating Limited Access does not fire updating post
> Fix post bugs

- package.json
- src/apiHandler/reactions.ts
- src/components/Page/Index.vue
- src/components/Page/Posts/Reactions.vue
- src/index.ts
- src/pages/Posts.astro
- Reactions now accept strings other than emojis. With this, Reactions is now a general purpose registry that can be counted per EOA.
- Emoji lists displayed as emoji reactions will be handled as before in `Reactions.vue`, and unintended emoji reactions does not appear in the UI.
> Flexible reactions

- package.json
- preview/config.ts
- preview/src/pages/[...page].astro
- preview/src/pages/admin/[...page].astro
- src/apiHandler/posts.ts
- src/components/Page/Contents/ContentsHead.vue
- src/components/Page/Index.vue
- src/index.ts
- src/pages/Posts.astro
- yarn.lock
`/posts/{FEED_ID}/{POST_ID}` now renders the single post page.
> Feat: Single post page

- package.json
- src/apiHandler/posts.ts
- src/apiHandler/search.ts
- src/components/Page/Index.vue
- src/fixtures/masking.ts
- src/fixtures/memberships.ts
- src/index.ts
Uses membershipVerifierFactory from core
> Permissions update

- src/components/Page/Contents/ContentsHead.vue
- src/components/Page/Contents/i18n/index.ts
now, share on hey.xyz🌿 directly from posts
> feat: add shareOnHey🌿

- package.json
- src/components/Common/Profile.vue
- src/index.ts
- yarn.lock
uses clubs-core to fetch profile
> uses clubs-core to fetch profile

- package.json
- src/components/Common/Profile.vue
- src/components/Page/Contents/Contents.vue
- src/components/Page/Contents/ContentsHead.vue
- src/components/Page/Index.vue
- src/components/Page/Posts/Comment.vue
- src/components/Page/Posts/Post.vue
- src/index.ts
instead of fetching profiles inside of the profile component, the following changes have been made:
- fetches profiles on the server
- maps them to an object like `{[address]: Profile}`
- passes down the profiles and maps them accordingly to their components
> fetches profiles server side and maps them accordingly

- package.json
- src/apiHandler/posts.ts
- src/index.ts
Needed to add some profile data for the API endpoint
> bugfix: Fetch profile on single post

- src/components/Page/Posts/Post/AddMedia.vue
- src/components/Page/Posts/Post/DoPost.vue
具体的には、AddMedia.vueファイルにてファイルアップロード後の処理に改善を加えました。また、DoPost.vueファイルから不要なログ表示と未使用のモジュールを削除しました。これらの変更により、コードの機能性と可読性が向上しています。
> メディアアップロードと投稿機能の改善
